---
version: 0.2
env:
  variables:
    JEKYLL_ENV: production
phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo "Installing requirements" && npm run install-reqs
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  base-directory: _site
  files:
    - '**/*'
